; PlatformIO Project Configuration File
; See https://docs.platformio.org/page/projectconf.html

[env:seeed_xiao_esp32c6]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = seeed_xiao_esp32c6
framework = arduino
monitor_speed = 115200
board_build.partitions = partitions_singleapp.csv

lib_deps =
    bblanchon/ArduinoJson @ ^7.0.4

build_flags = 
    -DARDUINO_SEEED_XIAO_ESP32C6
    -DBOARD_SCREEN_COMBO=512
    -DUSE_XIAO_EPAPER_DRIVER_BOARD
